- id: sunset_lights
  alias: Sunset Lights
  trigger:
    platform: sun
    event: sunset     
    offset: "-00:15:00"
  action:
     - service: light.turn_on
       data:
         entity_id: light.turret_lights 
         rgb_color: [255, 0, 200]
         brightness: 255         
     - service: light.turn_on
       data:
         entity_id: light.main_lights
         rgb_color: [100, 40, 0]
         brightness: 200



- id: lights_off_while_away
  alias: Turn Ligths Off At Night
  trigger:
    platform: time
    at: '22:30:00'
  action:
     - service: light.turn_off
       data:
         entity_id: light.bedroom_lights 
   

